const bannerCtrl = require("./banner.controller")
const uploader = require('../../middleware/uploader')
const router = require("express").Router()
const allowSeller = require('../../middleware/allowSeller')
router.post('/', allowSeller, uploader.single('image'), bannerCtrl.createBanner)
router.get('/', bannerCtrl.getAll)
router.get('/:id', bannerCtrl.listById)
router.get('/title/:title', bannerCtrl.listOne)
router.get('/user/:id', bannerCtrl.findforOneUser)
router.put('/:id', allowSeller, uploader.single('image'), bannerCtrl.updatebanner)
router.delete("/:id", allowSeller, bannerCtrl.deleteBanner)
module.exports = router